#!/bin/bash
#PBS -N segment005
#PBS -q develop
#PBS -l walltime=2:00:00
#PBS -A UWAS0155
#PBS -k eod
#PBS -l select=1:ncpus=5
#PBS -W depend=afterok:3918140.desched1
# ---------------------------------------------------------

source ~/.bashrc
module load conda
conda activate ppe-py
tdir="/glade/work/djk2120/ctsm_tether/tools/tether/"
$tdir"tether.sh" /glade/u/home/bbuchovecky/projects/cpl_ppe_co2/sims/coupPPE.004 commands.txt derecho.template
